http:
  routers:
    web-client:
      rule: "PathPrefix(`/`)"
      service: "web-client"
      middlewares:
        - "apiCompress"
      entryPoints:
        - "web"
    auth:
      rule: "PathPrefix(`/api/auth`)"
      service: "auth"
      middlewares:
        - "apiCompress"
      entryPoints:
        - "web"
    search:
      rule: "PathPrefix(`/api/search`)"
      service: "search"
      middlewares:
        - "apiStripPrefix"
        - "apiForwardAuth"
        - "apiCompress"
      entryPoints:
        - "web"
    api:
      rule: "PathPrefix(`/api/lootlog`)"
      service: "search"
      middlewares:
        - "apiStripPrefix"
        - "apiForwardAuth"
        - "apiCompress"
      entryPoints:
        - "web"
  services:
    web-client:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:3000"
    auth:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4001"
    search:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4002"
    api:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4003"
  middlewares:
    apiStripPrefix:
      stripPrefix:
        prefixes:
          - "/api/auth"
          - "/api/search"
          - "/api/lootlog"
    apiForwardAuth:
      forwardAuth:
        address: "http://host.docker.internal:4001/session"
        authResponseHeaders:
          - "X-Auth-User-Id"
          - "X-Auth-Discord-Id"
    apiCompress:
      compress:
        includedContentTypes:
          - application/json
          - text/html
          - text/plain