http:
  routers:
    web-client:
      rule: "PathPrefix(`/`)"
      service: "web-client"
      middlewares:
        - "apiCompress"
      entryPoints:
        - "web"
    auth:
      rule: "PathPrefix(`/api/auth`)"
      service: "auth"
      middlewares:
        - "apiStripPrefix"
        - "apiCompress"
        - "cors"
      entryPoints:
        - "web"
    search:
      rule: "PathPrefix(`/api/search`)"
      service: "search"
      middlewares:
        - "apiStripPrefix"
        - "apiForwardAuth"
        - "apiCompress"
        - "cors"
      entryPoints:
        - "web"
    api:
      rule: "PathPrefix(`/api/lootlog`)"
      service: "api"
      middlewares:
        - "apiStripPrefix"
        - "apiForwardAuth"
        - "apiCompress"
        - "cors"
      entryPoints:
        - "web"
  services:
    web-client:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:3000"
    auth:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4001"
    search:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4005"
    api:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:4003"
  middlewares:
    apiStripPrefix:
      stripPrefix:
        prefixes:
          - "/api/auth"
          - "/api/search"
          - "/api/lootlog"
    apiForwardAuth:
      forwardAuth:
        address: "http://host.docker.internal:4001/verify-auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-User-Id"
          - "X-Auth-Discord-Id"
    apiCompress:
      compress:
        includedContentTypes:
          - application/json
          - text/html
          - text/plain
    cors:
      headers:
        accessControlAllowOriginList:
          - "https://fobos.margonem.pl"
          - "http://localhost"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Auth-User-Id"
          - "X-Auth-Discord-Id"
        accessControlExposeHeaders:
          - "X-Auth-User-Id"
          - "X-Auth-Discord-Id"
        accessControlMaxAge: 86400